# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P4_ChecarPuedeVotar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 423)
        MainWindow.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 171, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../../3D Objects/UAT.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 0, 161, 51))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../3D Objects/facultad_ingenieria_tampico.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(590, 290, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../../3D Objects/Castor.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 140, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_edad = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_edad.setGeometry(QtCore.QRect(260, 130, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_edad.setFont(font)
        self.txt_edad.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:13px;")
        self.txt_edad.setText("")
        self.txt_edad.setObjectName("txt_edad")
        self.btn_comprobar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_comprobar.setGeometry(QtCore.QRect(210, 200, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_comprobar.setFont(font)
        self.btn_comprobar.setStyleSheet("background-color: #F39C12;\n"
"border-radius:13px;\n"
"color: rgb(255, 255, 255);")
        self.btn_comprobar.setObjectName("btn_comprobar")
        self.btn_salir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_salir.setGeometry(QtCore.QRect(350, 200, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_salir.setFont(font)
        self.btn_salir.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 4);\n"
"border-radius:13px;\n"
"")
        self.btn_salir.setObjectName("btn_salir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Edad:</span></p></body></html>"))
        self.btn_comprobar.setText(_translate("MainWindow", "Comprobar"))
        self.btn_salir.setText(_translate("MainWindow", "Salir"))
import Recursos_rc
